In [34]:
import pandas as pd

In [35]:
sel_df = pd.DataFrame({
                        'sal':[5000, 4500, 6000, 9000, 7000, 5500, 6200]
})

In [36]:
sel_df.describe()

               sal
count     7.000000
mean   6171.428571
std    1490.765224
min    4500.000000
25%    5250.000000
50%    6000.000000
75%    6600.000000
max    9000.000000

In [37]:
sel_df.loc[7,'sal'] = 170000

In [38]:
sel_df

        sal
0    5000.0
1    4500.0
2    6000.0
3    9000.0
4    7000.0
5    5500.0
6    6200.0
7  170000.0

In [39]:
sel_df.describe()

                 sal
count       8.000000
mean    26650.000000
std     57938.588177
min      4500.000000
25%      5375.000000
50%      6100.000000
75%      7500.000000
max    170000.000000